services:
  scraper:
    build: .
    image: asterix24/e-ink-scraper:0.1
    container_name: e-ink-scraper
    ipc: host
    env_file:
      - config.env

    volumes:
      - .:/app
      - /tmp:/tmp
    ports:
      - 8132:8312
      - 22000:22000

    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"

    environment:
      - PYTHONUNBUFFERED=1

    command: ./run-server.sh
