services:
  scraper:
    build: .
    image: asterix24/e-ink-scraper:0.1
    container_name: e-ink-scraper
    ipc: host
    env_file:
      - config.env

    volumes:
      - .:/app
    ports:
      - 8132:8312

    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"

    environment:
      - PYTHONUNBUFFERED=1

    command: python e-ink.py
